FROM alpine:3.7

RUN apk add --no-cache tzdata borgbackup bash lftp curl \
    && chmod 0600 /var/spool/cron/crontabs/root \
    && sed -i 's/\/root:\/bin\/ash/\/root:\/bin\/bash/g' /etc/passwd \
    && touch /var/log/backup.log \
    && ln -sf /dev/stdout /var/log/backup.log
