version: '3.4'

services:

  borg:
    container_name: docker-borgbackup-borg
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/script
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    working_dir: /script
    entrypoint: /bin/bash -c "tail -f /dev/null"
    env_file:
      - .env
